name: Release to dev
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    uses: cere-io/reusable-workflows/.github/workflows/deploy-to-cloudfront.yaml@master
    with:
      build_container: 'node:20-buster'
      install_packages_command: 'yarn install'
      build_command: 'yarn build'
      path_to_static_files_to_upload: 'packages/apps/build'
      s3_bucket_name: 'dev-cere-explorer-dist'
      aws_account_id: ${{ vars.DEV_NETWORK_AWS_ACCOUNT_ID }}
