name: Publish image to DockerHub
on:
  push:
    branches:
      - master

env:
  DOCKERHUB_REPOSITORY: cerebellumnetwork
  PACKAGE_NAME: block-viewer
jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and publish image
        run: |
          docker build . -t $DOCKERHUB_REPOSITORY/$PACKAGE_NAME:$GITHUB_SHA
          docker image tag $DOCKERHUB_REPOSITORY/$PACKAGE_NAME:$GITHUB_SHA $DOCKERHUB_REPOSITORY/$PACKAGE_NAME:latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish image to DockerHub
        id: docker_publish
        run: |
          docker push $DOCKERHUB_REPOSITORY/$PACKAGE_NAME:$GITHUB_SHA
          docker push $DOCKERHUB_REPOSITORY/$PACKAGE_NAME:latest
      - name: Image digest
        run: echo ${{ steps.docker_publish.outputs.digest }}
